#include "babble-lang.h"
#include "intrinsics.h"

extern intrinsic_info intrinsics [2];

#define GET_INTRINSIC(_ret, _symbol)                        \
{                                                           \
   (*_ret) = NULL;                                          \
    for (int i = 0;                                         \
        i < sizeof (intrinsics) / sizeof (intrinsic_info);  \
        i++) {                                              \
                                                            \
        if (!strcmp (intrinsics[i].symbol, _symbol)) {      \
            (*_ret) = intrinsics[i].source;                 \
            break;                                          \
        }                                                   \
    }                                                       \
}

static int init (FILE *out_file) {
    fprintf (out_file,
        "; ==========================================================\n"
        "; x86-64 Netwide assembly generated by Babble v%d.%d\n"
        "; ==========================================================\n\n",
        BABBLE_VER_MAJOR, BABBLE_VER_MINOR);
    
    // Initialize sections
    fprintf (out_file,
        "section .text\n"
        "global _start\n");
    
    int n_intrinsics = sizeof (intrinsics) / sizeof (intrinsic_info);
    // TODO: Put these in a separate `intrinsics.asm` file and include them in
    for (int i = 0; i < n_intrinsics; i++) {
        if (intrinsics[i].impl) {
            fprintf (out_file, "%s", intrinsics[i].source);
        }
    }
    fprintf (out_file,
        "_quit:\n"
        "mov rdi, 0\n"
        "mov rax, 60\n"
        "syscall\n");
    
    fprintf (out_file, "_start:\n");
}

static int assemble (int debug, const char *asm_name,
    const char *out_name) {

    char cmd_buf [1024];
    struct timeval ts;
    gettimeofday (&ts, NULL);
    snprintf (cmd_buf, 1024, "nasm -o %ld.o -f elf64%s %s", ts.tv_usec,
        (debug ? " -gdwarf" : ""), asm_name);
    
    int ret = system (cmd_buf);
    if (ret) {
        return BABBLE_ASSEMBLER_ERR;
    }

    snprintf (cmd_buf, 1024, "ld%s -o %s %ld.o", (debug ? " -g " : ""),
        out_name, ts.tv_usec);
    ret = system (cmd_buf);
    if (ret) {
        return BABBLE_LINKER_ERR;
    }

    snprintf (cmd_buf, 1024, "rm -f %ld.o", ts.tv_usec);
    system (cmd_buf);

    return BABBLE_OK;
}

int compile (int debug, const char *in_name,
    const char *out_name) {

    FILE *in_file = fopen (in_name, "r");
    if (in_file == NULL) {
        return BABBLE_FILE_NOT_FOUND;
    }
    
    struct timeval ts;
    gettimeofday (&ts, NULL);
    char asm_name [1024];
    memset (asm_name, 0x0, sizeof (asm_name));
    snprintf (asm_name, 1024, "%ld.asm", ts.tv_usec);

    char cmd_buf [1024];
    snprintf (cmd_buf, 1024, "rm -f %ld.asm", ts.tv_usec);
    system (cmd_buf);
    snprintf (cmd_buf, 1024, "touch %ld.asm", ts.tv_usec);
    system (cmd_buf);

    FILE *out_file = fopen (asm_name, "w");
    init (out_file);

    fprintf (out_file,
        "mov rax, 0\n"
        "push rax\n");

    char *temp;
    while (1) {
        char c = fgetc (in_file);
        if (feof (in_file)) {
            break;
        }
        if (isspace (c)) {
            continue;
        }
        switch (c) {
            case '+':
                fprintf (out_file,
                    "mov rax, [rsp]\n"
                    "inc rax\n"
                    "mov [rsp], rax\n");
                break;
            case '-':
                fprintf (out_file,
                    "mov rax, [rsp]\n"
                    "dec rax\n"
                    "mov [rsp], rax\n");
                break;
            case 'p':
                {
                    fprintf (out_file, "mov rdi, [rsp]\n");
                    GET_INTRINSIC (&temp, "print_i64");
                    assert (temp != NULL);
                    fprintf (out_file, "%s", temp); 
                }
        }
    }
    fprintf (out_file, "pop rax\n");
    fprintf (out_file, "call _quit\n");

    fclose (in_file);
    fclose (out_file);

    int ret = assemble (debug, asm_name, out_name);
    
    snprintf (cmd_buf, 1024, "rm -f %ld.asm", ts.tv_usec);
    system (cmd_buf);
    return ret;
}